{
    "total_num_contours": 11,
    "num_biggest_contours": 6,
    "num_detected_photos_on_mosaic": 3,
    "num_photos_on_mosaic": 3,
    "photos_areas": [374837493, 237827, 13823],
    "success": True,
    "picture_name": "mamie0037.jpg",
    "rm_black_edges": True,
    "add_white_margin": True,
    "blur_method": "GaussianBlur",
    "blur_kernel_size": (3, 3),
    "threshold": True,
    "threshold_method": "THRESH_BINARY_INV",
    "threshold_min": 240,
    "threshold_max": 255,
    "config_num": 12,
}
